# -*- coding: utf-8 -*-
"""DTW-Hirarki.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8yxyrsJAmIzBC9UItW_nKdhcx6e-h3b
"""

import numpy as np
import pandas as pd
import streamlit as st
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from scipy.spatial.distance import squareform
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
 
# ─────────────────────────────────────────────────────────────────────────────
#  PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="DTW Healthcare BEI",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)
 
# ─────────────────────────────────────────────────────────────────────────────
#  GLOBAL THEME
# ─────────────────────────────────────────────────────────────────────────────
DARK_BG       = "#0D1117"
CARD_BG       = "#161B22"
BORDER_CLR    = "#30363D"
ACCENT_BLUE   = "#58A6FF"
ACCENT_RED    = "#F78166"
ACCENT_GREEN  = "#3FB950"
ACCENT_GOLD   = "#E3B341"
ACCENT_PURPLE = "#BC8CFF"
ACCENT_CYAN   = "#39D0D8"
TEXT_MAIN     = "#E6EDF3"
TEXT_MUTE     = "#8B949E"
 
CLUSTER_COLORS = [ACCENT_BLUE, ACCENT_RED, ACCENT_GREEN, ACCENT_GOLD,
                  ACCENT_PURPLE, ACCENT_CYAN]
 
PLOTLY_LAYOUT = dict(
    paper_bgcolor=CARD_BG,
    plot_bgcolor=CARD_BG,
    font=dict(color=TEXT_MAIN, family="Inter, sans-serif"),
 
    legend=dict(bgcolor=CARD_BG, bordercolor=BORDER_CLR, borderwidth=1),
    margin=dict(l=40, r=20, t=50, b=40),
)
 
# ─────────────────────────────────────────────────────────────────────────────
#  CUSTOM CSS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
 
  html, body, [class*="css"] {{
      font-family: 'Inter', sans-serif;
      background-color: {DARK_BG};
      color: {TEXT_MAIN};
  }}
  .stApp {{ background-color: {DARK_BG}; }}
 
  /* Sidebar */
  [data-testid="stSidebar"] {{
      background-color: {CARD_BG};
      border-right: 1px solid {BORDER_CLR};
  }}
  [data-testid="stSidebar"] * {{ color: {TEXT_MAIN} !important; }}
 
  /* Cards */
  .metric-card {{
      background: {CARD_BG};
      border: 1px solid {BORDER_CLR};
      border-radius: 12px;
      padding: 18px 20px;
      text-align: center;
  }}
  .metric-card .label {{
      font-size: 11px;
      font-weight: 500;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: {TEXT_MUTE};
      margin-bottom: 6px;
  }}
  .metric-card .value {{
      font-size: 26px;
      font-weight: 700;
      line-height: 1;
  }}
  .metric-card .sub {{
      font-size: 11px;
      color: {TEXT_MUTE};
      margin-top: 4px;
  }}
 
  /* Section headers */
  .section-header {{
      font-size: 13px;
      font-weight: 600;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: {TEXT_MUTE};
      padding: 6px 0 10px 0;
      border-bottom: 1px solid {BORDER_CLR};
      margin-bottom: 16px;
  }}
 
  /* Page title */
  .hero {{
      background: linear-gradient(135deg, {CARD_BG} 0%, #1C2333 100%);
      border: 1px solid {BORDER_CLR};
      border-radius: 16px;
      padding: 28px 36px;
      margin-bottom: 24px;
      position: relative;
      overflow: hidden;
  }}
  .hero::before {{
      content: '';
      position: absolute;
      top: -40px; right: -40px;
      width: 200px; height: 200px;
      background: radial-gradient(circle, {ACCENT_BLUE}22 0%, transparent 70%);
  }}
  .hero h1 {{ font-size: 28px; font-weight: 700; margin: 0; color: {TEXT_MAIN}; }}
  .hero p  {{ font-size: 14px; color: {TEXT_MUTE}; margin: 6px 0 0 0; }}
 
  /* Cluster badges */
  .badge {{
      display: inline-block;
      padding: 2px 10px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 600;
      margin: 2px;
  }}
 
  /* Step progress */
  .step-done {{
      color: {ACCENT_GREEN};
      font-family: 'JetBrains Mono', monospace;
      font-size: 12px;
  }}
 
  /* Table */
  .stDataFrame {{ border-radius: 8px; overflow: hidden; }}
  thead tr th {{ background: {CARD_BG} !important; color: {TEXT_MUTE} !important; font-size: 11px !important; }}
  tbody tr:hover td {{ background: #21262D !important; }}
 
  /* Buttons & sliders */
  .stButton > button {{
      background: {ACCENT_BLUE};
      color: {DARK_BG};
      font-weight: 600;
      border: none;
      border-radius: 8px;
      padding: 8px 20px;
  }}
  .stButton > button:hover {{ background: #79BAFF; }}
 
  div[data-testid="stSelectbox"] > div,
  div[data-testid="stMultiSelect"] > div {{
      background: {CARD_BG};
      border-color: {BORDER_CLR};
      border-radius: 8px;
  }}
 
  /* Plotly charts full-width */
  .js-plotly-plot {{ border-radius: 10px; }}
</style>
""", unsafe_allow_html=True)
 
# ─────────────────────────────────────────────────────────────────────────────
#  CORE FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────
# HELPER UNTUK KONVERSI HEX KE RGBA
def hex_to_rgba(hex_code: str, alpha: float) -> str:
    hex_code = hex_code.lstrip('#')
    r = int(hex_code[0:2], 16)
    g = int(hex_code[2:4], 16)
    b = int(hex_code[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"

@st.cache_data(show_spinner=False)
def load_data(file_content: bytes) -> pd.DataFrame:
    import io
    df_raw = pd.read_csv(io.BytesIO(file_content), sep=";", index_col=0, header=0)
    df = df_raw.T.copy()
    df.index = pd.to_datetime(df.index, format="%d/%m/%Y %H:%M", errors="coerce")
    df = df.sort_index()
    df = df.apply(pd.to_numeric, errors="coerce")
    valid_cols = df.columns[df.isnull().mean() < 0.30]
    df = df[valid_cols].ffill().bfill()
    return df
 
 
@st.cache_data(show_spinner=False)
def normalize(df: pd.DataFrame) -> pd.DataFrame:
    df_norm = (df - df.mean()) / df.std()
    return df_norm.dropna(axis=1)
 
 
def dtw_distance(s1: np.ndarray, s2: np.ndarray, window: int = 30) -> float:
    n1, n2 = len(s1), len(s2)
    w = max(window, abs(n1 - n2))
    dtw_mat = np.full((n1 + 1, n2 + 1), np.inf)
    dtw_mat[0, 0] = 0.0
    for i in range(1, n1 + 1):
        for j in range(max(1, i - w), min(n2, i + w) + 1):
            cost = abs(s1[i - 1] - s2[j - 1])
            dtw_mat[i, j] = cost + min(dtw_mat[i-1, j], dtw_mat[i, j-1], dtw_mat[i-1, j-1])
    return dtw_mat[n1, n2]
 
 
def dtw_path(s1: np.ndarray, s2: np.ndarray):
    n1, n2 = len(s1), len(s2)
    dtw_mat = np.full((n1 + 1, n2 + 1), np.inf)
    dtw_mat[0, 0] = 0.0
    for i in range(1, n1 + 1):
        for j in range(1, n2 + 1):
            cost = abs(s1[i-1] - s2[j-1])
            dtw_mat[i, j] = cost + min(dtw_mat[i-1, j], dtw_mat[i, j-1], dtw_mat[i-1, j-1])
    path, i, j = [], n1, n2
    while i > 0 and j > 0:
        path.append((i-1, j-1))
        best = np.argmin([dtw_mat[i-1, j], dtw_mat[i, j-1], dtw_mat[i-1, j-1]])
        if best == 0: i -= 1
        elif best == 1: j -= 1
        else: i -= 1; j -= 1
    return dtw_mat[1:, 1:], list(reversed(path))
 
# PERBAIKAN: Hilangkan underscore '_' pada parameter agar cache di-reset saat data filter berubah
@st.cache_data(show_spinner=False)
def compute_dtw_matrix(df_norm: pd.DataFrame, window: int = 30) -> np.ndarray:
    tickers = df_norm.columns.tolist()
    n = len(tickers)
    data = df_norm.values.T
    dist_mat = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1, n):
            d = dtw_distance(data[i], data[j], window)
            dist_mat[i, j] = dist_mat[j, i] = d
    return dist_mat
 
# PERBAIKAN: Hilangkan underscore '_' pada parameter
@st.cache_data(show_spinner=False)
def run_clustering(dist_mat: np.ndarray, k: int):
    condensed = squareform(dist_mat)
    Z = linkage(condensed, method="ward")
    labels = fcluster(Z, k, criterion="maxclust")
    return Z, labels.tolist()
 
 
def leader_scores(dist_mat: np.ndarray) -> np.ndarray:
    scores = []
    for i in range(len(dist_mat)):
        row = dist_mat[i].copy(); row[i] = np.nan
        scores.append(1.0 / (np.nanmean(row) + 1e-9))
    return np.array(scores)
 
 
# ─────────────────────────────────────────────────────────────────────────────
#  SIDEBAR
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ Konfigurasi Analisis")
    st.markdown("---")
 
    uploaded = st.file_uploader(
        "📂 Upload CSV Harga Saham",
        type=["csv"],
        help="Format: baris = saham, kolom = tanggal, separator ';'"
    )
 
    st.markdown("**Parameter DTW**")
    dtw_window = st.slider("Window Sakoe-Chiba (hari)", 10, 60, 30,
                           help="Lebar band warping. Lebih besar = lebih fleksibel.")
    n_clusters  = st.slider("Jumlah Cluster (K)", 2, 8, 4)
 
    st.markdown("**Filter Tanggal**")
    use_date_filter = st.checkbox("Aktifkan filter tanggal", value=False)
 
    st.markdown("---")
    st.markdown(f"""
    <div style='font-size:11px; color:{TEXT_MUTE}; line-height:1.7'>
    📌 <b>Dynamic Time Warping</b> mengukur kemiripan dua deret waktu
    meski ada pergeseran fase / kecepatan berbeda.<br><br>
    📌 <b>Hierarchical Clustering</b> mengelompokkan saham berdasarkan
    jarak DTW menggunakan metode Ward.<br><br>
    📌 <b>Leader Score</b> = 1 / rata-rata jarak DTW ke semua saham lain.
    Makin tinggi → makin representatif.
    </div>
    """, unsafe_allow_html=True)
 
# ─────────────────────────────────────────────────────────────────────────────
#  HERO HEADER
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero">
  <h1>📈 DTW Analysis — Healthcare BEI</h1>
  <p>Dynamic Time Warping · Leader-Lagger Detection · Time Series Clustering · 2023–2026</p>
</div>
""", unsafe_allow_html=True)
 
# ─────────────────────────────────────────────────────────────────────────────
#  GUARD: file belum diupload
# ─────────────────────────────────────────────────────────────────────────────
if uploaded is None:
    st.markdown(f"""
    <div style="background:{CARD_BG}; border:1px dashed {BORDER_CLR}; border-radius:12px;
                padding:48px; text-align:center;">
      <div style="font-size:48px; margin-bottom:16px;">📂</div>
      <div style="font-size:18px; font-weight:600; color:{TEXT_MAIN}; margin-bottom:8px;">
        Upload file CSV untuk memulai analisis
      </div>
      <div style="font-size:13px; color:{TEXT_MUTE};">
        Gunakan sidebar kiri untuk mengunggah file
        <code>harga_penutupan_healthcare_bei_2023_2026.csv</code>
      </div>
    </div>
    """, unsafe_allow_html=True)
    st.stop()
 
# ─────────────────────────────────────────────────────────────────────────────
#  LOAD DATA
# ─────────────────────────────────────────────────────────────────────────────
with st.spinner("⏳ Memuat & membersihkan data…"):
    df_raw   = load_data(uploaded.read())
    df_norm0 = normalize(df_raw)
 
# Date filter
if use_date_filter:
    col_a, col_b = st.columns(2)
    d_min = df_raw.index.min().date()
    d_max = df_raw.index.max().date()
    date_start = col_a.date_input("Dari", value=d_min, min_value=d_min, max_value=d_max)
    date_end   = col_b.date_input("Sampai", value=d_max, min_value=d_min, max_value=d_max)
    df_raw  = df_raw.loc[str(date_start):str(date_end)]
    df_norm = normalize(df_raw)
else:
    df_norm = df_norm0
 
tickers = df_norm.columns.tolist()
n       = len(tickers)
 
# ─────────────────────────────────────────────────────────────────────────────
#  COMPUTE (with progress)
# ─────────────────────────────────────────────────────────────────────────────
prog_bar = st.progress(0, text="🔄 Menghitung matriks DTW…")
 
# PERBAIKAN: Hilangkan underscore '_' pada parameter agar cache di-reset dengan benar
@st.cache_data(show_spinner=False)
def full_compute(df_norm, window, k):
    dist_mat        = compute_dtw_matrix(df_norm, window)
    Z_link, labels  = run_clustering(dist_mat, k)
    scores          = leader_scores(dist_mat)
    return dist_mat, Z_link, labels, scores
 
dist_mat, Z_link, cluster_labels, scores = full_compute(df_norm, dtw_window, n_clusters)
prog_bar.progress(100, text="✅ Kalkulasi selesai!")
prog_bar.empty()
 
# Build lookup structures
cluster_map = {t: cluster_labels[i] for i, t in enumerate(tickers)}
leader_df   = pd.DataFrame({
    "Saham"  : tickers,
    "Cluster": [cluster_map[t] for t in tickers],
    "Skor"   : scores,
}).sort_values("Skor", ascending=False).reset_index(drop=True)
 
top_leader = leader_df.iloc[0]["Saham"]
top_lagger = leader_df.iloc[-1]["Saham"]
 
pairs_sorted = sorted(
    [(tickers[i], tickers[j], dist_mat[i, j])
     for i in range(n) for j in range(i+1, n)],
    key=lambda x: x[2]
)
 
# ─────────────────────────────────────────────────────────────────────────────
#  KPI CARDS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown('<div class="section-header">📊 Ringkasan Analisis</div>', unsafe_allow_html=True)
 
c1, c2, c3, c4, c5, c6 = st.columns(6)
def kpi(col, label, value, sub="", color=ACCENT_BLUE):
    col.markdown(f"""
    <div class="metric-card">
      <div class="label">{label}</div>
      <div class="value" style="color:{color}">{value}</div>
      <div class="sub">{sub}</div>
    </div>""", unsafe_allow_html=True)
 
kpi(c1, "Total Saham",    n,               f"{df_norm.shape[0]} hari bursa", ACCENT_BLUE)
kpi(c2, "Cluster",        n_clusters,      f"Ward Linkage",                   ACCENT_PURPLE)
kpi(c3, "Leader Utama",   top_leader.replace(".JK",""), f"Skor {leader_df['Skor'].iloc[0]:.4f}", ACCENT_GREEN)
kpi(c4, "Lagger Utama",   top_lagger.replace(".JK",""), f"Skor {leader_df['Skor'].iloc[-1]:.4f}", ACCENT_RED)
kpi(c5, "Pasangan Mirip", pairs_sorted[0][0].replace(".JK","")+"↔"+pairs_sorted[0][1].replace(".JK",""),
    f"DTW = {pairs_sorted[0][2]:.1f}", ACCENT_GOLD)
kpi(c6, "Window DTW",     f"{dtw_window}h", "Sakoe-Chiba band",               ACCENT_CYAN)
 
st.markdown("<br>", unsafe_allow_html=True)
 
# ─────────────────────────────────────────────────────────────────────────────
#  TAB LAYOUT
# ─────────────────────────────────────────────────────────────────────────────
tabs = st.tabs([
    "① Harga Saham",
    "② Matriks DTW",
    "③ Dendrogram",
    "④ Leader–Lagger",
    "⑤ Cluster Trend",
    "⑥ DTW Pair Viewer",
    "⑦ Data & Export",
])
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 1 — HARGA SAHAM NORMALIZED
# ══════════════════════════════════════════════════════════════════════════════
with tabs[0]:
    st.markdown('<div class="section-header">① Harga Penutupan Ternormalisasi (Z-Score)</div>',
                unsafe_allow_html=True)

    col_ctrl1, col_ctrl2 = st.columns([3, 1])
    selected_tickers = col_ctrl1.multiselect(
        "Pilih saham (kosong = semua)",
        options=tickers,
        default=[],
        format_func=lambda x: x.replace(".JK", ""),
    )
    show_cluster_only = col_ctrl2.selectbox(
        "Filter cluster",
        ["Semua"] + [f"Cluster {k}" for k in range(1, n_clusters + 1)],
    )

    display_tickers = selected_tickers if selected_tickers else tickers
    if show_cluster_only != "Semua":
        ck = int(show_cluster_only.split()[-1])
        display_tickers = [t for t in display_tickers if cluster_map[t] == ck]

    fig1 = go.Figure()
    for t in display_tickers:
        c_idx = (cluster_map[t] - 1) % len(CLUSTER_COLORS)
        fig1.add_trace(go.Scatter(
            x=df_norm.index, y=df_norm[t],
            name=t.replace(".JK", ""),
            line=dict(color=CLUSTER_COLORS[c_idx], width=1.3),
            opacity=0.8,
            hovertemplate=f"<b>{t}</b><br>%{{x|%d %b %Y}}<br>Z-Score: %{{y:.2f}}<extra></extra>",
        ))
    fig1.add_hline(y=0, line_dash="dash", line_color=TEXT_MUTE, opacity=0.4)
    fig1.update_layout(
        **PLOTLY_LAYOUT,
        height=420,
        title="Harga Saham Healthcare BEI — Normalized Z-Score",
        xaxis_title="Tanggal",
        yaxis_title="Z-Score",
        hovermode="x unified"
    )
    fig1.update_xaxes(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR)
    fig1.update_yaxes(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR)
    st.plotly_chart(fig1, use_container_width=True)

    # Mini table: first/last price & change
    st.markdown('<div class="section-header">Ringkasan Harga Per Saham</div>',
                unsafe_allow_html=True)
    summary_rows = []
    for t in tickers:
        first = df_raw[t].dropna().iloc[0]  if t in df_raw else None
        last  = df_raw[t].dropna().iloc[-1] if t in df_raw else None
        chg   = ((last - first) / first * 100) if (first and last and first != 0) else None
        summary_rows.append({
            "Saham"      : t,
            "Cluster"    : cluster_map[t],
            "Harga Awal" : f"Rp {first:,.0f}" if first else "-",
            "Harga Akhir": f"Rp {last:,.0f}"  if last  else "-",
            "Perubahan"  : f"{chg:+.1f}%" if chg is not None else "-",
            "Leader Rank": int(leader_df[leader_df["Saham"] == t].index[0]) + 1,
        })
    df_summary = pd.DataFrame(summary_rows)
    st.dataframe(df_summary, use_container_width=True, hide_index=True,
                 column_config={
                     "Perubahan": st.column_config.TextColumn("Perubahan (%)", help="Dari awal hingga akhir periode"),
                     "Cluster": st.column_config.NumberColumn("Cluster", format="%d"),
                 })
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 2 — DTW HEATMAP
# ══════════════════════════════════════════════════════════════════════════════
with tabs[1]:
    st.markdown('<div class="section-header">② Matriks Jarak DTW Antar Saham</div>',
                unsafe_allow_html=True)
 
    sort_by = st.radio("Urut berdasarkan", ["Cluster", "Leader Score", "Abjad"],
                       horizontal=True)
    if sort_by == "Cluster":
        order = leader_df.sort_values(["Cluster","Skor"], ascending=[True, False])["Saham"].tolist()
    elif sort_by == "Leader Score":
        order = leader_df["Saham"].tolist()
    else:
        order = sorted(tickers)
 
    idx_o   = [tickers.index(t) for t in order]
    dm_ord  = dist_mat[np.ix_(idx_o, idx_o)]
    labels_o = [t.replace(".JK","") for t in order]
 
    fig2 = go.Figure(go.Heatmap(
        z=dm_ord, x=labels_o, y=labels_o,
        colorscale=[[0, ACCENT_GREEN], [0.5, CARD_BG], [1, ACCENT_RED]],
        hovertemplate="<b>%{y}</b> ↔ <b>%{x}</b><br>DTW Distance: %{z:.1f}<extra></extra>",
        colorbar=dict(
            title=dict(text="Jarak DTW", font=dict(color=TEXT_MAIN)),
            tickfont=dict(color=TEXT_MAIN),
        ),
    ))
 
    # Cluster separator lines
    prev = 0
    for k in range(1, n_clusters + 1):
        cnt = sum(1 for t in order if cluster_map[t] == k)
        x0  = prev - 0.5
        x1  = prev + cnt - 0.5
        fig2.add_shape(type="rect",
                       x0=x0, y0=x0, x1=x1, y1=x1,
                       line=dict(color=CLUSTER_COLORS[k-1], width=2),
                       fillcolor="rgba(0,0,0,0)")
        fig2.add_annotation(
            x=(x0 + x1) / 2, y=-1.2,
            text=f"C{k}", showarrow=False,
            font=dict(color=CLUSTER_COLORS[k-1], size=10),
        )
        prev += cnt
 
    fig2.update_layout(**PLOTLY_LAYOUT, height=580,
                       title="DTW Distance Matrix — dikelompokkan per Cluster")
    
    fig2.update_layout(
        xaxis=dict(
            tickangle=-45, 
            tickfont=dict(size=9),
            gridcolor="rgba(0,0,0,0)",
            zerolinecolor="rgba(0,0,0,0)"
        ),
        yaxis=dict(
            tickfont=dict(size=9), 
            autorange="reversed",
            gridcolor="rgba(0,0,0,0)",
            zerolinecolor="rgba(0,0,0,0)"
        ),
    )
    st.plotly_chart(fig2, use_container_width=True)
 
    # Top-N similar pairs table
    st.markdown('<div class="section-header">Top Pasangan Saham Paling Mirip & Paling Berbeda</div>',
                unsafe_allow_html=True)
    n_top = st.slider("Tampilkan N pasangan", 5, 20, 10)
    col_sim, col_dif = st.columns(2)
 
    with col_sim:
        st.markdown(f"<div style='color:{ACCENT_GREEN}; font-weight:600; font-size:13px;'>🟢 Paling Mirip (DTW terkecil)</div>", unsafe_allow_html=True)
        df_sim = pd.DataFrame(pairs_sorted[:n_top], columns=["Saham A","Saham B","DTW Distance"])
        df_sim["DTW Distance"] = df_sim["DTW Distance"].round(2)
        st.dataframe(df_sim, use_container_width=True, hide_index=True)
 
    with col_dif:
        st.markdown(f"<div style='color:{ACCENT_RED}; font-weight:600; font-size:13px;'>🔴 Paling Berbeda (DTW terbesar)</div>", unsafe_allow_html=True)
        df_dif = pd.DataFrame(pairs_sorted[-n_top:][::-1], columns=["Saham A","Saham B","DTW Distance"])
        df_dif["DTW Distance"] = df_dif["DTW Distance"].round(2)
        st.dataframe(df_dif, use_container_width=True, hide_index=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 3 — DENDROGRAM
# ══════════════════════════════════════════════════════════════════════════════
with tabs[2]:
    st.markdown('<div class="section-header">③ Dendrogram Hierarchical Clustering (Ward Linkage)</div>',
                unsafe_allow_html=True)
 
    # Render dendrogram via matplotlib (plotly dendrogram not as pretty)
    fig_dend, ax = plt.subplots(figsize=(14, 6), facecolor=CARD_BG)
    ax.set_facecolor(CARD_BG)
 
    color_list = [CLUSTER_COLORS[(k-1) % len(CLUSTER_COLORS)] for k in range(1, n_clusters+1)]
    threshold_val = Z_link[-(n_clusters - 1), 2] if n_clusters > 1 else Z_link[-1, 2]
 
    from scipy.cluster.hierarchy import set_link_color_palette
    set_link_color_palette(CLUSTER_COLORS[:n_clusters])
 
    dend = dendrogram(
        Z_link,
        labels=[t.replace(".JK","") for t in tickers],
        ax=ax,
        color_threshold=threshold_val,
        above_threshold_color=TEXT_MUTE,
        leaf_font_size=9,
        leaf_rotation=45,
    )
    ax.axhline(threshold_val, color=ACCENT_GOLD, lw=1.5, ls="--", alpha=0.8,
               label=f"Threshold K={n_clusters}")
    ax.set_xlabel("Saham", color=TEXT_MUTE, fontsize=10)
    ax.set_ylabel("Jarak DTW (Ward)", color=TEXT_MUTE, fontsize=10)
    ax.set_title(f"Dendrogram — {n_clusters} Cluster", color=TEXT_MAIN, fontsize=13)
    ax.tick_params(colors=TEXT_MUTE)
    for sp in ax.spines.values(): sp.set_edgecolor(BORDER_CLR)
    ax.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, fontsize=9)
    plt.tight_layout()
    st.pyplot(fig_dend, use_container_width=True)
    plt.close()
 
    # Cluster membership cards
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">Komposisi Cluster</div>', unsafe_allow_html=True)
    cols_c = st.columns(n_clusters)
    for k in range(1, n_clusters + 1):
        members = [t for t, c in cluster_map.items() if c == k]
        # medoid
        idx_m  = [tickers.index(m) for m in members]
        sub_dm = dist_mat[np.ix_(idx_m, idx_m)]
        medoid = members[int(np.argmin(sub_dm.sum(axis=1)))]
        color  = CLUSTER_COLORS[(k-1) % len(CLUSTER_COLORS)]
        badge_html = "".join(
            f'<span class="badge" style="background:{color}22; color:{color}; border:1px solid {color}55">'
            f'{t.replace(".JK","")}</span>'
            for t in members
        )
        cols_c[k-1].markdown(f"""
        <div class="metric-card" style="border-color:{color}55; text-align:left;">
          <div style="color:{color}; font-weight:700; font-size:14px; margin-bottom:8px;">
            Cluster {k} &nbsp; <span style="font-size:11px; color:{TEXT_MUTE};">{len(members)} saham</span>
          </div>
          <div style="margin-bottom:8px; font-size:11px; color:{TEXT_MUTE};">
            Medoid: <b style="color:{color}">{medoid.replace('.JK','')}</b>
          </div>
          {badge_html}
        </div>""", unsafe_allow_html=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 4 — LEADER / LAGGER
# ══════════════════════════════════════════════════════════════════════════════
with tabs[3]:
    st.markdown('<div class="section-header">④ Leader–Lagger Score</div>', unsafe_allow_html=True)
 
    # Bar chart
    colors_bar = [CLUSTER_COLORS[(cluster_map[t]-1) % len(CLUSTER_COLORS)] for t in leader_df["Saham"]]
    fig4 = go.Figure(go.Bar(
        x=leader_df["Skor"],
        y=[t.replace(".JK","") for t in leader_df["Saham"]],
        orientation="h",
        marker=dict(color=colors_bar, line=dict(color=BORDER_CLR, width=0.5)),
        text=leader_df["Skor"].round(5).astype(str),
        textposition="outside",
        textfont=dict(size=10, color=TEXT_MUTE),
        hovertemplate="<b>%{y}</b><br>Leader Score: %{x:.5f}<extra></extra>",
    ))
    fig4.add_vline(x=leader_df["Skor"].mean(), line_dash="dash", line_color=ACCENT_GOLD,
                   annotation_text="Rata-rata", annotation_font=dict(color=ACCENT_GOLD))
    
    fig4.update_layout(**PLOTLY_LAYOUT, height=620,
                       title="Leader Score — Semakin Tinggi = Semakin Representatif (Leader)",
                       xaxis_title="Leader Score (1 / rata-rata jarak DTW)",
                       bargap=0.25)
    
    fig4.update_layout(
        xaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
        yaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
    )
 
    # Annotations for top & bottom
    fig4.add_annotation(
        x=leader_df["Skor"].iloc[0],
        y=leader_df["Saham"].iloc[0].replace(".JK",""),
        text="⭐ LEADER", showarrow=True, ax=60, ay=0,
        font=dict(color=ACCENT_GREEN, size=11),
        arrowcolor=ACCENT_GREEN,
    )
    fig4.add_annotation(
        x=leader_df["Skor"].iloc[-1],
        y=leader_df["Saham"].iloc[-1].replace(".JK",""),
        text="🐢 LAGGER", showarrow=True, ax=60, ay=0,
        font=dict(color=ACCENT_RED, size=11),
        arrowcolor=ACCENT_RED,
    )
    st.plotly_chart(fig4, use_container_width=True)
 
    # Scatter: leader score vs return
    st.markdown('<div class="section-header">Leader Score vs. Return Periode</div>',
                unsafe_allow_html=True)
    scatter_data = []
    for t in tickers:
        if t in df_raw.columns:
            prices = df_raw[t].dropna()
            ret    = (prices.iloc[-1] / prices.iloc[0] - 1) * 100 if len(prices) > 1 else 0
        else:
            ret = 0
        scatter_data.append({
            "Saham"  : t.replace(".JK",""),
            "Skor"   : leader_df[leader_df["Saham"]==t]["Skor"].values[0],
            "Return" : ret,
            "Cluster": cluster_map[t],
        })
    df_sc = pd.DataFrame(scatter_data)
 
    fig4b = px.scatter(
        df_sc, x="Skor", y="Return",
        text="Saham", color="Cluster",
        color_discrete_sequence=CLUSTER_COLORS,
        size_max=14,
        hover_data={"Saham": True, "Skor": ":.5f", "Return": ":.1f"},
        labels={"Skor": "Leader Score", "Return": "Total Return (%)"},
        title="Leader Score vs. Total Return per Saham",
    )
    fig4b.update_traces(textposition="top center", textfont=dict(size=9))
    fig4b.add_hline(y=0, line_dash="dash", line_color=TEXT_MUTE, opacity=0.4)
    fig4b.update_layout(**PLOTLY_LAYOUT, height=400)
    fig4b.update_layout(
        xaxis=dict(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR),
        yaxis=dict(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR),
    )
    st.plotly_chart(fig4b, use_container_width=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 5 — CLUSTER TREND
# ══════════════════════════════════════════════════════════════════════════════
with tabs[4]:
    st.markdown('<div class="section-header">⑤ Tren Rata-rata Per Cluster</div>',
                unsafe_allow_html=True)
 
    # Mean + std band per cluster
    fig5 = go.Figure()
    for k in range(1, n_clusters + 1):
        members = [t for t, c in cluster_map.items() if c == k]
        mean_s  = df_norm[members].mean(axis=1)
        std_s   = df_norm[members].std(axis=1)
        color   = CLUSTER_COLORS[(k-1) % len(CLUSTER_COLORS)]
        
        fig5.add_trace(go.Scatter(
            x=df_norm.index, y=mean_s,
            name=f"Cluster {k} ({len(members)} saham)",
            line=dict(color=color, width=2.5),
            hovertemplate=f"<b>Cluster {k}</b><br>%{{x|%d %b %Y}}<br>Z-Score: %{{y:.2f}}<extra></extra>",
        ))
        
        # PERBAIKAN: Menggunakan hex_to_rgba untuk memastikan format string warna valid untuk plotly fillcolor
        fig5.add_trace(go.Scatter(
            x=pd.concat([df_norm.index.to_series(), df_norm.index.to_series()[::-1]]),
            y=pd.concat([mean_s + std_s, (mean_s - std_s)[::-1]]),
            fill="toself",
            fillcolor=hex_to_rgba(color, 0.15),
            line=dict(color="rgba(0,0,0,0)"),
            showlegend=False,
            hoverinfo="skip",
        ))
        
    fig5.add_hline(y=0, line_dash="dot", line_color=TEXT_MUTE, opacity=0.3)
    fig5.update_layout(**PLOTLY_LAYOUT, height=420,
                       title="Rata-rata Harga Per Cluster ± 1 Std Dev",
                       xaxis_title="Tanggal", yaxis_title="Z-Score",
                       hovermode="x unified")
    fig5.update_layout(
        xaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
        yaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
    )
    st.plotly_chart(fig5, use_container_width=True)
 
    # Individual cluster deep-dive
    st.markdown('<div class="section-header">Deep-Dive: Saham dalam Satu Cluster</div>',
                unsafe_allow_html=True)
    sel_cluster = st.selectbox("Pilih Cluster", range(1, n_clusters + 1),
                               format_func=lambda k: f"Cluster {k}")
    cluster_members = [t for t, c in cluster_map.items() if c == sel_cluster]
 
    fig5b = go.Figure()
    for t in cluster_members:
        fig5b.add_trace(go.Scatter(
            x=df_norm.index, y=df_norm[t],
            name=t.replace(".JK",""),
            mode="lines",
            line=dict(width=1.5),
            hovertemplate=f"<b>{t}</b><br>%{{x|%d %b %Y}}<br>%{{y:.2f}}<extra></extra>",
        ))
    fig5b.update_layout(**PLOTLY_LAYOUT, height=380,
                        title=f"Cluster {sel_cluster} — Individual Saham",
                        xaxis_title="Tanggal", yaxis_title="Z-Score",
                        hovermode="x unified")
    fig5b.update_layout(
        xaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
        yaxis=dict(
            gridcolor=BORDER_CLR, 
            zerolinecolor=BORDER_CLR,
            showgrid=True,
            showline=False
        ),
    )
    st.plotly_chart(fig5b, use_container_width=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 6 — DTW PAIR VIEWER (INTERACTIVE)
# ══════════════════════════════════════════════════════════════════════════════
with tabs[5]:
    st.markdown('<div class="section-header">⑥ DTW Pair Comparison — Warping Path Visualizer</div>',
                unsafe_allow_html=True)
 
    col_p1, col_p2, col_p3 = st.columns([2, 2, 1])
    t1_sel = col_p1.selectbox("Saham 1", tickers, index=0,
                               format_func=lambda x: x.replace(".JK",""))
    t2_options = [t for t in tickers if t != t1_sel]
    t2_sel = col_p2.selectbox("Saham 2", t2_options, index=0,
                               format_func=lambda x: x.replace(".JK",""))
    subsample = col_p3.slider("Subsample", 50, 200, 100, step=10,
                               help="Titik data untuk visualisasi warping path")
 
    d_val = dist_mat[tickers.index(t1_sel), tickers.index(t2_sel)]
    st.markdown(
        f"<div style='margin-bottom:12px; font-size:13px;'>"
        f"Jarak DTW <b style='color:{ACCENT_GOLD}'>{t1_sel.replace('.JK','')} ↔ {t2_sel.replace('.JK','')}</b>"
        f" = <b style='color:{ACCENT_BLUE}; font-size:18px'>{d_val:.2f}</b>"
        f"&nbsp;&nbsp;|&nbsp;&nbsp;Rank kemiripan: <b>#{next((i+1 for i,(a,b,_) in enumerate(pairs_sorted) if (a==t1_sel and b==t2_sel) or (a==t2_sel and b==t1_sel)), '—')}</b>"
        f" dari {len(pairs_sorted)} pasangan</div>",
        unsafe_allow_html=True
    )
 
    s1_raw = df_norm[t1_sel].values
    s2_raw = df_norm[t2_sel].values
    step   = max(1, len(s1_raw) // subsample)
    s1s    = s1_raw[::step]
    s2s    = s2_raw[::step]
    dates_s = df_norm.index[::step]
    ns     = min(len(dates_s), len(s1s), len(s2s))
 
    with st.spinner("Menghitung warping path…"):
        _, path = dtw_path(s1s[:ns], s2s[:ns])
 
    fig6 = make_subplots(rows=2, cols=1, row_heights=[0.7, 0.3],
                         shared_xaxes=False, vertical_spacing=0.06)
 
    # Top: dual-axis line chart
    fig6.add_trace(go.Scatter(
        x=dates_s[:ns], y=s1s[:ns], name=t1_sel.replace(".JK",""),
        line=dict(color=ACCENT_BLUE, width=2),
        hovertemplate=f"<b>{t1_sel}</b><br>%{{x|%d %b %Y}}<br>%{{y:.2f}}<extra></extra>",
    ), row=1, col=1)
    fig6.add_trace(go.Scatter(
        x=dates_s[:ns], y=s2s[:ns], name=t2_sel.replace(".JK",""),
        line=dict(color=ACCENT_RED, width=2),
        hovertemplate=f"<b>{t2_sel}</b><br>%{{x|%d %b %Y}}<br>%{{y:.2f}}<extra></extra>",
    ), row=1, col=1)
 
    # Warping path lines (sampled)
    for pi, pj in path[::max(1, len(path)//60)]:
        if pi < ns and pj < ns:
            fig6.add_trace(go.Scatter(
                x=[dates_s[pi], dates_s[pj]],
                y=[s1s[pi],     s2s[pj]],
                mode="lines",
                line=dict(color=ACCENT_GOLD, width=0.5),
                opacity=0.25,
                showlegend=False,
                hoverinfo="skip",
            ), row=1, col=1)
 
    # Bottom: warping path heatmap (cost difference)
    # PERBAIKAN: Menggunakan hex_to_rgba untuk fillcolor
    diff = np.abs(s1s[:ns] - s2s[:ns])
    fig6.add_trace(go.Scatter(
        x=dates_s[:ns], y=diff,
        fill="tozeroy",
        name="│S1−S2│",
        line=dict(color=ACCENT_GOLD, width=1.2),
        fillcolor=hex_to_rgba(ACCENT_GOLD, 0.15),
        hovertemplate="%{x|%d %b %Y}<br>Selisih: %{y:.3f}<extra></extra>",
    ), row=2, col=1)
 
    fig6.update_layout(
        paper_bgcolor=CARD_BG, plot_bgcolor=CARD_BG,
        font=dict(color=TEXT_MAIN),
        height=560,
        title=f"DTW Alignment: {t1_sel.replace('.JK','')} vs {t2_sel.replace('.JK','')}  — Jarak DTW = {d_val:.2f}",
        legend=dict(bgcolor=CARD_BG, bordercolor=BORDER_CLR, borderwidth=1),
        margin=dict(l=40, r=20, t=50, b=40),
    )
    fig6.update_xaxes(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR, showgrid=True)
    fig6.update_yaxes(gridcolor=BORDER_CLR, zerolinecolor=BORDER_CLR, showgrid=True)
    fig6.update_yaxes(title_text="Z-Score", row=1, col=1)
    fig6.update_yaxes(title_text="|S1-S2|", row=2, col=1)
 
    st.plotly_chart(fig6, use_container_width=True)
 
    # Quick stats comparison
    st.markdown('<div class="section-header">Statistik Perbandingan</div>', unsafe_allow_html=True)
    cmp_a, cmp_b = st.columns(2)
    for col_w, tk, color in [(cmp_a, t1_sel, ACCENT_BLUE), (cmp_b, t2_sel, ACCENT_RED)]:
        ser = df_raw[tk].dropna() if tk in df_raw else pd.Series([])
        col_w.markdown(f"""
        <div class="metric-card" style="border-color:{color}55; text-align:left;">
          <div style="color:{color}; font-weight:700; font-size:15px; margin-bottom:10px;">{tk}</div>
          <table style="width:100%; font-size:12px; color:{TEXT_MUTE}; border-collapse:collapse;">
            <tr><td>Harga Awal</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.iloc[0]:,.0f}</td></tr>
            <tr><td>Harga Akhir</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.iloc[-1]:,.0f}</td></tr>
            <tr><td>Minimum</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.min():,.0f}</td></tr>
            <tr><td>Maksimum</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.max():,.0f}</td></tr>
            <tr><td>Rata-rata</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.mean():,.0f}</td></tr>
            <tr><td>Std Deviasi</td><td style="color:{TEXT_MAIN}; text-align:right">Rp {ser.std():,.0f}</td></tr>
            <tr><td>Total Return</td>
              <td style="color:{ACCENT_GREEN if (ser.iloc[-1]/ser.iloc[0]-1)>0 else ACCENT_RED}; text-align:right">
                {(ser.iloc[-1]/ser.iloc[0]-1)*100:+.2f}%</td></tr>
            <tr><td>Cluster</td><td style="color:{TEXT_MAIN}; text-align:right">{cluster_map[tk]}</td></tr>
          </table>
        </div>""", unsafe_allow_html=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
#  TAB 7 — DATA & EXPORT
# ══════════════════════════════════════════════════════════════════════════════
with tabs[6]:
    st.markdown('<div class="section-header">⑦ Data Mentah & Export Hasil</div>',
                unsafe_allow_html=True)
 
    export_tab1, export_tab2, export_tab3 = st.tabs(["📋 Tabel Ranking", "🗂️ Matriks Jarak", "📈 Data Harga"])
 
    with export_tab1:
        st.markdown("**Ranking Lengkap Leader–Lagger**")
        df_export_rank = leader_df.copy()
        df_export_rank["Saham"] = df_export_rank["Saham"].str.replace(".JK","")
        df_export_rank["Skor"]  = df_export_rank["Skor"].round(6)
        st.dataframe(df_export_rank, use_container_width=True, hide_index=True)
        csv1 = df_export_rank.to_csv(index=False).encode()
        st.download_button("⬇️ Download CSV Ranking", csv1,
                           "dtw_leader_lagger_ranking.csv", "text/csv")
 
    with export_tab2:
        st.markdown("**Matriks Jarak DTW (N × N)**")
        df_dm = pd.DataFrame(dist_mat.round(2),
                             index=[t.replace(".JK","") for t in tickers],
                             columns=[t.replace(".JK","") for t in tickers])
        st.dataframe(df_dm, use_container_width=True)
        csv2 = df_dm.to_csv().encode()
        st.download_button("⬇️ Download Matriks DTW", csv2,
                           "dtw_distance_matrix.csv", "text/csv")
 
    with export_tab3:
        st.markdown("**Harga Asli (Rp)**")
        st.dataframe(df_raw.rename(columns=lambda x: x.replace(".JK","")),
                     use_container_width=True)
        csv3 = df_raw.to_csv().encode()
        st.download_button("⬇️ Download Harga CSV", csv3,
                           "harga_saham_raw.csv", "text/csv")
 
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">Tentang Dashboard</div>', unsafe_allow_html=True)
    st.markdown(f"""
    <div style="background:{CARD_BG}; border:1px solid {BORDER_CLR}; border-radius:12px; padding:20px;
                font-size:13px; color:{TEXT_MUTE}; line-height:1.9;">
    <b style="color:{TEXT_MAIN}">📐 Metodologi:</b><br>
    &nbsp;&nbsp;• <b>DTW (Dynamic Time Warping)</b>: mengukur kemiripan dua time series dengan memperbolehkan
      pergeseran waktu menggunakan Sakoe-Chiba band (window = {dtw_window} hari).<br>
    &nbsp;&nbsp;• <b>Hierarchical Clustering (Ward)</b>: mengelompokkan saham berdasarkan jarak DTW;
      K={n_clusters} cluster.<br>
    &nbsp;&nbsp;• <b>Leader Score</b> = 1 / (rata-rata jarak DTW ke semua saham lain).
      Saham dengan skor tinggi adalah "pusat gravitasi" sektor.<br><br>
    <b style="color:{TEXT_MAIN}">📊 Data:</b> {len(df_raw)} hari bursa,
      {df_raw.index.min().date()} – {df_raw.index.max().date()},
      {n} emiten sektor Healthcare BEI.<br><br>
    <b style="color:{TEXT_MAIN}">🛠️ Stack:</b> Python · Streamlit · Plotly · SciPy · NumPy · Pandas
    </div>
    """, unsafe_allow_html=True)
